name: py36zl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pandas=0.22.0
  - jupyter
  - cvxopt
  - matplotlib
  - seaborn
  - zipline
  - scikit-learn
  - dill
  - xlrd<2.0
  #- openpyxl
  #- xlwt
  - pip:
    - pandas==0.22.0
    - requests
    - xlsxwriter
    - tqdm
    - watermark
    - pyfolio
    - numba
    - importlib_resources
    #- xlsxwriter
